////////////////////////////////////////////////////////////////////
// This file is automatically generated
// Do not edit manually
////////////////////////////////////////////////////////////////////

import React from 'react';
import ReactDOM from 'react-dom';

{% for widget in widgets -%}
import { default as {{ widget.componentName }} } from '../widgets/{{ widget.componentName }}/{{ widget.componentName }}';
{% endfor %}

var widgets = require('@jupyter-widgets/base');
var _ = require('lodash');

{% for widget in widgets %}
export class {{ widget.componentName }}Model extends widgets.DOMWidgetModel {
    defaults = _.extend(widgets.DOMWidgetModel.prototype.defaults(), {
        _model_name : '{{ widget.componentName }}Model',
        _view_name : '{{ widget.componentName }}View',
        _model_module : '{{ extension_name }}_jup',
        _view_module : '{{ extension_name }}_jup',
        _model_module_version : '{{ version }}',
        _view_module_version : '{{ version }}',

        // Props
        _props: {},

        // Python state
        {% for name in widget.pythonStateKeys -%}
        {{ name }}: '',
        {% endfor %}

        // JavaScript state
        {% for name in widget.javaScriptStateKeys -%}
        {{ name }}: '',
        {% endfor %}

        __dummy: ''
    })
}

// Custom View. Renders the widget model.
export class {{ widget.componentName }}View extends widgets.DOMWidgetView {
    render() {
        this.div=document.createElement('div');
        this.el.appendChild(this.div);

        ReactDOM.render(
            <{{ widget.componentName }} jupyterModel={this.model} {...this.model.get('_props')} />,
            this.div
        );
    }
}
{% endfor %}
