####################################################################
## This file is automatically generated
## Do not edit manually
####################################################################

from .all_widgets import *
from .widgets.jupyter import *

from ._version import __version__

def _jupyter_nbextension_paths():
    return [{
        'section': 'notebook',
        'src': 'static',
        'dest': '{{ project_name }}_jup',
        'require': '{{ project_name }}_jup/extension'
    }]

def init_jupyter():
    from IPython.display import Javascript
    import os
    dirname = os.path.dirname(os.path.realpath(__file__))

    fname = os.path.join(dirname, 'dist', 'bundle.js')
    with open(fname, 'rb') as f:
        js = f.read().decode('utf-8')
    # display(Javascript(requirejs + '\n\n' + js))
    display(Javascript(js))
    print('Initialized {{ project_name }} for Jupyter notebooks')
