####################################################################
## This file is automatically generated
## Do not edit manually
####################################################################

from reactopya_jup import ReactopyaWidget

{% for widget in widgets -%}
from .widgets import {{ widget.componentName }} as {{ widget.componentName }}Orig
{% endfor %}

{% for widget in widgets %}
class {{ widget.componentName }}:
    """Jupyter widget for {{ widget.componentName }}"""

    def __init__(self, **kwargs):
        super().__init__()
        self._props = kwargs
        self._X = {{ widget.componentName }}Orig()
        self._reactopya_widget = ReactopyaWidget(
            component=self._X,
            component_name='{{ widget.componentName }}',
            props=kwargs
        )
    
    def _reactopya_widget(self):
        return self._reactopya_widget

    def show(self):
        self._reactopya_widget.show()
{% endfor %}