####################################################################
## This file is automatically generated
## Do not edit manually
####################################################################

from .all_widgets import *

from ._version import __version__
