////////////////////////////////////////////////////////////////////
// This file is automatically generated
// Do not edit manually
////////////////////////////////////////////////////////////////////

var path = require('path');
var version = require('./package.json').version;

var rules = [
    { test: /\.css$/, use: ['style-loader', 'css-loader']}
]

module.exports = [
    {
        entry: ['./js/index.js'],
        output: {
            filename: 'bundle.js',
            path: path.resolve(__dirname, '{{ project_name }}_colab', 'dist')
        },
        module: {
            rules: rules
        }
    }
];
