####################################################################
# This file is automatically generated
# Do not edit manually
####################################################################

from .BaseWidget import _BaseWidget

{% for widget in widgets -%}
from .widgets import {{ widget.type }} as {{ widget.type }}Orig
{% endfor %}

{% for widget in widgets %}
class {{ widget.type }}(_BaseWidget):
    """Jupyter widget for {{ widget.type }}"""

    def __init__(self, *args, **kwargs):
        super().__init__({{ widget.type }}Orig, '{{ widget.type }}', '{{ project_name }}', *args, **kwargs)

if hasattr({{ widget.type }}Orig, 'examples'):
    setattr({{ widget.type }}, 'examples', {{ widget.type }}Orig.examples)

{% endfor %}
