FROM ubuntu:18.04

#########################################
### Python                                                               
RUN apt-get update && apt-get -y install git wget build-essential
RUN apt-get install -y python3 python3-pip
RUN ln -s python3 /usr/bin/python
RUN ln -s pip3 /usr/bin/pip
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-tk

#########################################
### Node and yarn
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get update && apt-get install -y nodejs
RUN npm install -g yarn

#########################################
### Numpy
RUN pip install numpy

#########################################
### JupyterLab
RUN pip install jupyterlab

#########################################
### Install reactopya_jup
RUN pip install --upgrade reactopya_jup
RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
RUN jupyter labextension install reactopya_jup

#########################################
### Install {{ project_name }}
RUN pip install --upgrade {{ project_name }}=={{ version }}

CMD jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
