////////////////////////////////////////////////////////////////////
// This file is automatically generated
// Do not edit manually
////////////////////////////////////////////////////////////////////

var widgets = require('@jupyter-widgets/base');
var _ = require('lodash');
const version = require('../package.json').version;

class ReactopyaWidgetModel extends widgets.DOMWidgetModel {
    initialize(attributes, options) {
        super.initialize(attributes, options);
        let that = this;
        this.listenTo(this, 'msg:custom', _.bind(this.handleMessage, this));
        this.javaScriptPythonStateModel = new JavaScriptPythonStateModel();
        this.javaScriptPythonStateModel.onJavaScriptStateChanged(function(state) {
            that.send({
                name: 'setJavaScriptState',
                state: state
            });
        });
    }
    handleMessage(content) {
        const name = content.name;
        if (name == 'setPythonState') {
            let state = content.state;
            this.javaScriptPythonStateModel.setPythonState(state);
        }
        else {
            console.error(`Unregognized message in Model: ${name}`);
        }
        
    }
    defaults() {
        return _.extend(widgets.DOMWidgetModel.prototype.defaults(), {
            _model_name : 'ReactopyaWidgetModel',
            _view_name : 'ReactopyaWidgetView',
            _model_module : 'reactopya_jup',
            _view_module : 'reactopya_jup',
            _model_module_version : version,
            _view_module_version : version,

            _component_name: 'unknown',
            _props: {}
        });
    }
}

// Custom View. Renders the widget model.
class ReactopyaWidgetView extends widgets.DOMWidgetView {
    initialize(parameters) {
        super.initialize(parameters);
    }
    render() {
        this.div=document.createElement('div');
        this.el.appendChild(this.div);

        const componentName = this.model.get('_component_name');
        let props = this.model.get('_props');
        props.javaScriptPythonStateModel = this.model.javaScriptPythonStateModel;
        window.reactopya.widgets[componentName].render(this.div, props);
    }
}

class JavaScriptPythonStateModel {
    constructor() {
        this._pythonStateStringified = {};
        this._javaScriptStateStringified = {};
        this._pythonStateChangedHandlers = [];
        this._javaScriptStateChangedHandlers = [];
    }
    setPythonState(state) {
        this._setStateHelper(state, this._pythonStateStringified, this._pythonStateChangedHandlers);
    }
    setJavaScriptState(state) {
        this._setStateHelper(state, this._javaScriptStateStringified, this._javaScriptStateChangedHandlers);
    }
    onPythonStateChanged(handler) {
        this._pythonStateChangedHandlers.push(handler);
    }
    onJavaScriptStateChanged(handler) {
        this._javaScriptStateChangedHandlers.push(handler);
    }
    _setStateHelper(state, existingStateStringified, handlers) {
        let changedState = {};
        let somethingChanged = false;
        for (let key in state) {
            let val = state[key];
            let valstr = JSON.stringify(val);
            if (valstr !== existingStateStringified[key]) {
                existingStateStringified[key] = val;
                changedState[key] = JSON.parse(valstr);
                somethingChanged = true;
            }
        }
        if (somethingChanged) {
            for (let handler of handlers) {
                handler(changedState);
            }
        }
    }
}

module.exports = {
    ReactopyaWidgetModel: ReactopyaWidgetModel,
    ReactopyaWidgetView: ReactopyaWidgetView
};